<template>
  <div>
    <h3 id="id-10.摘自《云栖社区》-十六.开发工具类">十六. 开发工具类</h3>
    <ol>
      <li>
        <p>前端开发工具</p>
        <ul>
          <li>
            <a
              href="https://github.com/judasn/IntelliJ-IDEA-Tutorial"
              class="external-link"
              rel="nofollow"
            >IntelliJ IDEA 简体中文专题教程</a>
          </li>
          <li>
            <a
              href="http://t.cn/8kZZ1Uy"
              class="external-link"
              rel="nofollow"
            >Webstorm,InterllIdea,Phpstorm</a>
          </li>
          <li>
            <a
              href="https://github.com/jikeytang/sublime-text"
              class="external-link"
              rel="nofollow"
            >SublimeText</a>
          </li>
          <li>
            <a href="https://atom.io/" class="external-link" rel="nofollow">Atom</a>
          </li>
          <li>
            <a
              href="https://code.visualstudio.com/"
              class="external-link"
              rel="nofollow"
            >visual studio code</a>
          </li>
        </ul>
      </li>
      <li>
        <p>Chrome, Firebug, Filddle 调试</p>
        <ol>
          <li>
            <p>Fiddler</p>
            <ul>
              <li>
                <a
                  href="http://www.cnblogs.com/tugenhua0707/p/4623317.html"
                  class="external-link"
                  rel="nofollow"
                >Fiddler调式使用知多少(一)深入研究</a>
              </li>
              <li>
                <a
                  href="http://www.cnblogs.com/strick/p/4570006.html"
                  class="external-link"
                  rel="nofollow"
                >微信fiddle</a>
              </li>
              <li>
                <a
                  href="http://gaoboy.com/article/26.html"
                  class="external-link"
                  rel="nofollow"
                >微信fiddle</a>
              </li>
              <li>[]()</li>
            </ul>
          </li>
          <li>
            <p>Chrome</p>
            <ul>
              <li>
                <a
                  href="https://developer.chrome.com/devtools"
                  class="external-link"
                  rel="nofollow"
                >Google Chrome 官方</a>
              </li>
              <li>
                <a
                  href="http://www.cnblogs.com/constantince/p/4565261.html"
                  class="external-link"
                  rel="nofollow"
                >Chrome - 基础</a>
              </li>
              <li>
                <a
                  href="http://www.cnblogs.com/constantince/p/4579121.html"
                  class="external-link"
                  rel="nofollow"
                >Chrome - 进阶</a>
              </li>
              <li>
                <a
                  href="http://www.cnblogs.com/constantince/p/4585983.html"
                  class="external-link"
                  rel="nofollow"
                >Chrome - 性能</a>
              </li>
              <li>
                <a
                  href="http://www.cnblogs.com/constantince/p/4607497.html"
                  class="external-link"
                  rel="nofollow"
                >Chrome - 性能进阶</a>
              </li>
              <li>
                <a
                  href="http://www.cnblogs.com/constantince/p/4624241.html"
                  class="external-link"
                  rel="nofollow"
                >Chrome - 移动</a>
              </li>
              <li>
                <a
                  href="http://www.cnblogs.com/liyunhua/p/4544738.html"
                  class="external-link"
                  rel="nofollow"
                >Chrome - 使用技巧</a>
              </li>
              <li>
                <a
                  href="http://www.cnblogs.com/Wayou/p/chrome-console-tips-and-tricks.html"
                  class="external-link"
                  rel="nofollow"
                >Chrome - Console控制台不完全指南</a>
              </li>
              <li>
                <a
                  href="http://c7sky.com/chrome-devtools-workspace.html"
                  class="external-link"
                  rel="nofollow"
                >Chrome - Workspace使浏览器变成IDE</a>
              </li>
              <li>
                <a
                  href="http://www.html-js.com/article/Nothing-blind%202975"
                  class="external-link"
                  rel="nofollow"
                >network面板</a>
              </li>
              <li>
                <a
                  href="http://anti-code.com/devtools-cheatsheet/"
                  class="external-link"
                  rel="nofollow"
                >chrome开发工具快捷键</a>
              </li>
              <li>
                <a
                  href="http://www.html-js.com/article/2327"
                  class="external-link"
                  rel="nofollow"
                >chrome调试工具常用功能整理</a>
              </li>
              <li>
                <a
                  href="http://www.iinterest.net/2014/05/09/chrome-dev-tool-workspace/"
                  class="external-link"
                  rel="nofollow"
                >Chrome 开发工具 Workspace 使用</a>
              </li>
              <li>
                <a
                  href="http://www.cppblog.com/deercoder/archive/2011/10/22/158886.html"
                  class="external-link"
                  rel="nofollow"
                >Chrome神器Vimium快捷键学习记录</a>
              </li>
              <li>
                <a
                  href="http://www.w3cplus.com/sassguide/debug.html"
                  class="external-link"
                  rel="nofollow"
                >sass调试-w3cplus</a>
              </li>
              <li>
                <a
                  href="http://www.w3cplus.com/tools/how-to-use-chrome-devtools-like-a-pro.html"
                  class="external-link"
                  rel="nofollow"
                >如何更专业的使用Chrome开发者工具-w3cplus</a>
              </li>
              <li>
                <a
                  href="http://sentsin.com/web/253.html"
                  class="external-link"
                  rel="nofollow"
                >chrome调试canvas</a>
              </li>
              <li>
                <a
                  href="https://developer.chrome.com/devtools/index"
                  class="external-link"
                  rel="nofollow"
                >chrome profiles1</a>
              </li>
              <li>
                <a
                  href="http://h5dev.uc.cn/article-25-1.html"
                  class="external-link"
                  rel="nofollow"
                >chrome profiles2</a>
              </li>
              <li>
                <a
                  href="http://www.oschina.net/translate/performance-optimisation-with-timeline-profiles"
                  class="external-link"
                  rel="nofollow"
                >chrome profiles3</a>
              </li>
              <li>
                <a
                  href="https://developer.chrome.com/devtools/docs/mobile-emulation"
                  class="external-link"
                  rel="nofollow"
                >chrome移动版调试</a>
              </li>
              <li>
                <a
                  href="http://ued.taobao.org/blog/2012/06/debug-with-chrome-dev-tool/"
                  class="external-link"
                  rel="nofollow"
                >chrome调试</a>
              </li>
              <li>
                <a
                  href="http://www.cnblogs.com/QLeelulu/archive/2011/08/28/2156402.html"
                  class="external-link"
                  rel="nofollow"
                >chrome的调试</a>
              </li>
              <li>
                <a
                  href="https://developer.chrome.com/devtools/docs/commandline-api"
                  class="external-link"
                  rel="nofollow"
                >chrome console 命令详解</a>
              </li>
              <li>
                <a
                  href="http://www.cnblogs.com/leonkao/p/3809655.html"
                  class="external-link"
                  rel="nofollow"
                >查看事件绑定1</a>
              </li>
              <li>
                <a
                  href="http://www.cnblogs.com/xiaoyao2011/p/3447421.html"
                  class="external-link"
                  rel="nofollow"
                >查看事件绑定2</a>
              </li>
              <li>
                <a
                  href="http://segmentfault.com/a/1190000000683599"
                  class="external-link"
                  rel="nofollow"
                >神器——Chrome开发者工具(一)</a>
              </li>
              <li>
                <a
                  href="https://xinranliu.me/2015-05-22-qiqu-performance/"
                  class="external-link"
                  rel="nofollow"
                >奇趣百科性能优化(Chrome DevTools 中的 Timeline Profils 等工具使用介绍)</a>
              </li>
              <li>
                <a
                  href="http://frontenddev.org/link/15-tips-of-chrome-developer-tools.html"
                  class="external-link"
                  rel="nofollow"
                >chrome 开发者工具的 15 个小技巧</a>
              </li>
              <li>
                <a
                  href="http://1ke.co/course/361"
                  class="external-link"
                  rel="nofollow"
                >Chrome开发者工具不完全指南</a>
              </li>
              <li>
                <a
                  href="http://segmentfault.com/a/1190000003882567"
                  class="external-link"
                  rel="nofollow"
                >Chrome 开发者工具使用技巧</a>
              </li>
            </ul>
          </li>
          <li>
            <p>Firebug</p>
            <ul>
              <li>
                <a
                  href="http://www.imooc.com/learn/137"
                  class="external-link"
                  rel="nofollow"
                >firebug视频教程</a>
              </li>
              <li>
                <a
                  href="https://developer.mozilla.org/zh-CN/docs/Tools/WebIDE"
                  class="external-link"
                  rel="nofollow"
                >firefox 模拟器</a>
              </li>
              <li>
                <a
                  href="http://www.cnblogs.com/ctriphire/p/4116207.html"
                  class="external-link"
                  rel="nofollow"
                >console.log 命令详解</a>
              </li>
              <li>
                <a
                  href="http://www.ruanyifeng.com/blog/2008/06/firebug_tutorial.html"
                  class="external-link"
                  rel="nofollow"
                >Firebug入门指南</a>
              </li>
              <li>
                <a
                  href="http://www.ruanyifeng.com/blog/2011/03/firebug_console_tutorial.html"
                  class="external-link"
                  rel="nofollow"
                >Firebug控制台详解</a>
              </li>
              <li>[]()</li>
            </ul>
          </li>
          <li>
            <p>移动,微信调试</p>
            <ul>
              <li>
                <a href="https://openstf.github.io/" class="external-link" rel="nofollow">浏览器端调试安卓</a>
              </li>
              <li>
                <a
                  href="http://yujiangshui.com/multidevice-frontend-debug/"
                  class="external-link"
                  rel="nofollow"
                >移动端前端开发调试</a>
              </li>
              <li>
                <a
                  href="https://github.com/yujiangshui/CN-Chrome-DevTools/blob/remote-debugging/md/Use-Tools/remote-debugging.md"
                  class="external-link"
                  rel="nofollow"
                >使用 Chrome 远程调试 Android 设备</a>
              </li>
              <li>
                <a
                  href="http://plus.uc.cn/document/webapp/doc5.html"
                  class="external-link"
                  rel="nofollow"
                >mac移动端调试</a>
              </li>
              <li>
                <a href="http://www.mihtool.com/" class="external-link" rel="nofollow">mac移动端调试</a>
              </li>
              <li>
                <a
                  href="http://thx.github.io/mobile/debugging-in-mobile/"
                  class="external-link"
                  rel="nofollow"
                >无线调试攻略</a>
              </li>
              <li>
                <a
                  href="http://yanhaijing.com/mobile/2014/12/17/web-debug-for-mobile/"
                  class="external-link"
                  rel="nofollow"
                >无线调试攻略</a>
              </li>
              <li>
                <a
                  href="http://www.jianshu.com/p/ccf124f1f74b"
                  class="external-link"
                  rel="nofollow"
                >屌爆了,完美调试 微信webview(x5)</a>
              </li>
              <li>
                <a
                  href="http://liyaodong.com/2015/07/06/%E5%BE%AE%E4%BF%A1%E8%B0%83%E8%AF%95%E7%9A%84%E9%82%A3%E4%BA%9B%E4%BA%8B/"
                  class="external-link"
                  rel="nofollow"
                >微信调试的那些事</a>
              </li>
              <li>
                <a href="http://jsconsole.com/" class="external-link" rel="nofollow">远程console</a>
              </li>
              <li>
                <a href="http://blog.qqbrowser.cc/" class="external-link" rel="nofollow">微信调试工具</a>
              </li>
              <li>
                <a
                  href="https://github.com/jieyou/remote_inspect_web_on_real_device"
                  class="external-link"
                  rel="nofollow"
                >各种真机远程调试方法汇总</a>
              </li>
            </ul>
          </li>
          <li>
            <p>iOS Simulator</p>
            <ul>
              <li>
                <a
                  href="https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/iOS_Simulator_Guide/Introduction/Introduction.html"
                  class="external-link"
                  rel="nofollow"
                >Simulator</a>
              </li>
              <li>
                <a
                  href="http://www.crifan.com/intro_ios_simulator_in_xcode_and_usage_summary/"
                  class="external-link"
                  rel="nofollow"
                >Xcode中的iOS模拟器(iOS Simulator)的介绍和使用心得</a>
              </li>
            </ul>
          </li>
        </ol>
      </li>
      <li>
        <p>img</p>
        <ul>
          <li>
            <a
              href="http://preloaders.net/en/circular"
              class="external-link"
              rel="nofollow"
            >loading img</a>
          </li>
          <li>
            <a href="http://zhitu.isux.us/" class="external-link" rel="nofollow">智图-图片优化平台</a>
          </li>
          <li>
            <a href="https://tinypng.com/" class="external-link" rel="nofollow">在线png优化</a>
          </li>
        </ul>
      </li>
      <li>
        <p>生成二维码</p>
        <ul>
          <li>
            <a href="http://cli.im/" class="external-link" rel="nofollow">生成二维码</a>
          </li>
        </ul>
      </li>
      <li>
        <p>浏览器同步</p>
        <ul>
          <li>
            <a href="https://github.com/leeluolee/puer" class="external-link" rel="nofollow">puer</a>
          </li>
          <li>
            <a href="http://livereload.com/" class="external-link" rel="nofollow">liveReload</a>
          </li>
          <li>
            <a href="http://getf5.com/" class="external-link" rel="nofollow">f5</a>
          </li>
          <li>
            <a href="http://geek100.com/2608/" class="external-link" rel="nofollow">File Watchers</a>
          </li>
        </ul>
      </li>
      <li>
        <p>在线PPT制作</p>
        <ul>
          <li>
            <a
              href="http://js8.in/2013/11/16/%E6%8E%A8%E8%8D%90nodeppt%EF%BC%9A%E4%BD%BF%E7%94%A8markdown%E8%AF%AD%E6%B3%95%E6%9D%A5%E5%86%99%E7%BD%91%E9%A1%B5ppt/"
              class="external-link"
              rel="nofollow"
            >nodePPT</a>
          </li>
          <li>
            <a href="https://github.com/ksky521/nodePPT" class="external-link" rel="nofollow">PPT</a>
          </li>
          <li>
            <a
              href="https://github.com/hakimel/reveal.js/"
              class="external-link"
              rel="nofollow"
            >reveal</a>
          </li>
          <li>
            <a href="https://github.com/Seldaek/slippy" class="external-link" rel="nofollow">slippy</a>
          </li>
        </ul>
      </li>
    </ol>
  </div>
</template>
